### ISSUE TITLE
VMM Plugin for VRL-Studio cannot be opened more than once

### ISSUE THREAD

**Issue by miho** [miho/VMM#1]
Opening the VRL-Plugin version of the VMM editor causes the following exception:

``` java
Exception in thread "JavaFX Application Thread" java.lang.Error: factory already defined
    at java.net.URL.setURLStreamHandlerFactory(URL.java:1105)
    at eu.mihosoft.vrl.mmd.editor.MainWindowController.initialize(MainWindowController.java:140)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
    at eu.mihosoft.vrl.mmd.editor.Main.showEditor(Main.java:60)
    at eu.mihosoft.vrl.mmd.editor.Main.lambda$showEditor$0(Main.java:47)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by miho** [comment]
Seems to work since we moved `setURLStreamHandlerFactory()` to static initializer.

**TODO:** what if other plugins want to set their own factory?
