### ISSUE TITLE
NoClassDefFoundError Exception on Linux x64, JDK 8u66

### ISSUE THREAD

**Issue by miho** [miho/VMM#2]
``` java
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: eu/mihosoft/vrl/mmd/VSysUtil
        at eu.mihosoft.vrl.mmd.editor.TextControlUtil.getSystemControlModifier(TextControlUtil.java:48)
        at eu.mihosoft.vrl.mmd.editor.MainWindowController.initMenu(MainWindowController.java:442)
        at eu.mihosoft.vrl.mmd.editor.MainWindowController.initialize(MainWindowController.java:105)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at eu.mihosoft.vrl.mmd.editor.Main.showEditor(Main.java:60)
        at eu.mihosoft.vrl.mmd.editor.Main.lambda$showEditor$0(Main.java:47)
```

How to reproduce: open VRL-Studio, click on `Tools->VMM-Editor`. No window will appear. The exception is thrown instead.

**Comment by miho** [comment]
Might be a problem with the `exportPackage()` in plugin configurator.
